module.exports = {
  types: {
    WORK_ORDER_ASSIGNED: "WORK_ORDER_ASSIGNED",
    WORK_ORDER_COMPLETED: "WORK_ORDER_COMPLETED",
    WORK_ORDER_ACCEPTED: "WORK_ORDER_ACCEPTED",
    WORK_ORDER_DECLINED: "WORK_ORDER_DECLINED",
    INVOICE_UPLOADED: "INVOICE_UPLOADED",
    INVOICE_UPLOAD_PENDING: "INVOICE_UPLOAD_PENDING",
    KEY_RETURNED: "KEY_RETURNED",
    KEY_RETURN_PENDING: "KEY_RETURN_PENDING",
    DUE_DATE_EXTENSION_REQUESTED: "DUE_DATE_EXTENSION_REQUESTED",
    DUE_DATE_EXTENSION_REVIEWED: "DUE_DATE_EXTENSION_REVIEWED",
    INSPECTION_REQUEST_ASSIGNED: "INSPECTION_REQUEST_ASSIGNED",
    WORK_ORDER_ASSIGNED_CLERK: "WORK_ORDER_ASSIGNED_CLERK",
    TASK_ASSIGNED_CLERK: "TASK_ASSIGNED_CLERK",
    TODO_ASSIGNED_CLERK: "TODO_ASSIGNED_CLERK",
    WORK_ORDER_ALL_VENDORS_DECLINED: "WORK_ORDER_ALL_VENDORS_DECLINED",
    SERVICE_AGREEMENT_ALL_VENDORS_DECLINED:
      "SERVICE_AGREEMENT_ALL_VENDORS_DECLINED",
    SERVICE_AGREEMENT_ASSIGNED: "SERVICE_AGREEMENT_ASSIGNED",
    SERVICE_AGREEMENT_NEW_CYCLE_CREATED: "SERVICE_AGREEMENT_NEW_CYCLE_CREATED",
    SERVICE_AGREEMENT_FINAL_INVOICE_CHECK:
      "SERVICE_AGREEMENT_FINAL_INVOICE_CHECK",
  },
  events: {
    WORK_ORDER_COMPLETED: { roles: ["Admin", "OfficeAdmin", "RepairsTeam"] },
    INVOICE_UPLOADED: { roles: ["Admin", "OfficeAdmin", "AccountsTeam"] },
    KEY_RETURNED: { roles: ["Admin", "OfficeAdmin", "RepairsTeam"] },
    WORK_ORDER_ALL_VENDORS_DECLINED: { roles: ["Admin", "OfficeAdmin"] },
    SERVICE_AGREEMENT_ALL_VENDORS_DECLINED: { roles: ["Admin", "OfficeAdmin"] },
    DUE_DATE_EXTENSION_REQUESTED: {
      roles: ["Admin", "OfficeAdmin", "RepairsTeam"],
    },
    SERVICE_AGREEMENT_NEW_CYCLE_CREATED: {
      roles: ["Admin", "OfficeAdmin", "RepairsTeam"],
    },
    SERVICE_AGREEMENT_FINAL_INVOICE_CHECK: {
      roles: ["Admin", "OfficeAdmin", "AccountsTeam"],
    },
  },
};
